### PR TITLE
update iron dependency to v0.4

### PR DESCRIPTION
**Pull request by flosse**

### CODE REVIEW

**Comment by XMPPwocky** [comment]
Hey, I'm away from my main PC right now, will do this ASAP. Do you want to
take over maintainer here? Not sure if I can transfer a crate on crates.io.

**Comment by flosse** [comment]
> Do you want to take over maintainer here? 

I'm quite busy but I could try to be faster as you ;-)

> Not sure if I can transfer a crate on crates.io.

I guess `cargo owner --add flosse` should do the job :)

**Comment by XMPPwocky** [comment]
Done. Sorry about that.

**Comment by untitaker** [comment]
Any update on this?

**Comment by flosse** [comment]
@untitaker sorry! Now it's on crates.io :)

**Comment by untitaker** [comment]
Thanks!

**Comment by untitaker** [comment]
@flosse You forgot to push to master I suspect.

**Comment by flosse** [comment]
@untitaker I  did: https://github.com/flosse/oven ;-)

**Comment by untitaker** [comment]
I see, could we transfer this repo or add something to the readme too?

**Comment by flosse** [comment]
This depends on @XMPPwocky if he's willing to continue this repo or not. To be honest, I'd be glad if I don't have to maintain it but I could do it anyway if no body else is interested in it ;-)

**Comment by untitaker** [comment]
I might be able to help out as well, but I think everybody having their own fork is the worst.

**Comment by flosse** [comment]
> I might be able to help out as well

cool

> but I think everybody having their own fork is the worst.

I totally agree!

**Comment by XMPPwocky** [comment]
I thought I transferred this to @flosse - though I think they need to
accept?

**Comment by flosse** [comment]
> I thought I transferred this to @flosse - though I think they need to
> accept?

This worked for crates.io so there is nothing more to be done.
But related to github there is a `Transfer ownership` button in the settings menu that might work to redirect the visitors to the new place (I never tried it so).

**Comment by flosse** [comment]
... I just deleted my `oven` repo so there should be no conflict :)

**Comment by XMPPwocky** [comment]
Yeah, transfer repo on GitHub is what I did. Will try when I'm at my PC
again tonight.

**Comment by flosse** [comment]
It worked :) THX!

**Pull request closed without merging**
